Repository fga-eps-mds/2020.1-stay-safe-secretary-service, pull requests merged in 2020-10, with the labels that each got.

#22 Fix bug on test_get_crimes_by_crime_nature
  src/tests/test_crime.py
Labels: bug

#24 Change the valid filters
  src/controllers/crime.py
Labels: bug

#31 Refactor DF and SP spiders to catch monthly data
  src/controllers/.gitkeep
  src/controllers/crime.py
  src/crawlers/crimes/crimes/items.py
  src/crawlers/crimes/crimes/pipelines.py
  src/crawlers/crimes/crimes/spiders/crimesDF.py
  src/crawlers/crimes/crimes/spiders/crimesSP.py
  src/crawlers/crimes/utils/crimes_nature.py
  src/crawlers/crimes/utils/dates.py
  src/crawlers/crimes/utils/treat_data_df.py
  src/crawlers/crimes/utils/treat_data_sp.py
  src/static/swagger.json
  src/tests/.gitkeep
  src/tests/test_crime.py
  src/utils/.gitkeep
Labels: enhancement

#30 Create population data json.
  src/static_data/populationData.json
Labels: feature

#38 Add new filters on crime endpoint
  src/controllers/crime.py
  src/static/swagger.json
  src/static_data/populationData.json
  src/tests/test_crime.py
  src/utils/amount_crimes.py
  src/utils/constants.py
  src/utils/valid_months.py
  src/utils/validators/validate_filters.py
  src/views/crime.py
Labels: feature
